#!/bin/bash
RTAIDIR=`rtai-config --prefix`

sudo insmod $RTAIDIR/modules/rtai_hal.ko
sudo insmod $RTAIDIR/modules/rtai_lxrt.ko
sudo insmod $RTAIDIR/modules/rtai_wd.ko Policy=0 Limit=-1 Safety=-1 LooperTimeLimit=1000
sudo insmod $RTAIDIR/modules/rtai_sem.ko
sudo insmod $RTAIDIR/modules/rtai_mbx.ko
sudo insmod $RTAIDIR/modules/rtai_msg.ko
sudo insmod $RTAIDIR/modules/rtai_netrpc.ko ThisNode="127.0.0.1"
