#!/bin/sh

RTAIDIR=`rtai-config --prefix`

usage () {
	echo "Usage: "
    echo "./rtai_modules_ctrl load: load the modules"
	echo "./rtai_modules_ctrl remove: remove the modules"
	echo "./rtai_modules_ctrl status: status of the rtai modules loaded."
	exit
}

status () {
	lsmod | grep rtai
}

insmodules () {	
	sudo insmod $RTAIDIR/modules/rtai_hal.ko
	sudo insmod $RTAIDIR/modules/rtai_lxrt.ko
	sudo insmod $RTAIDIR/modules/rtai_wd.ko Policy=0 Limit=-1 Safety=-1 LooperTimeLimit=1000
	sudo insmod $RTAIDIR/modules/rtai_sem.ko
	sudo insmod $RTAIDIR/modules/rtai_mbx.ko
	sudo insmod $RTAIDIR/modules/rtai_msg.ko
	sudo insmod $RTAIDIR/modules/rtai_netrpc.ko ThisSoftNode="127.0.0.1"
}

rmmodules() {
	sudo rmmod rtai_netrpc
	sudo rmmod rtai_msg
	sudo rmmod rtai_mbx
	sudo rmmod rtai_sem
	sudo rmmod rtai_wd
	sudo rmmod rtai_lxrt
	sudo rmmod rtai_hal
}

#Test permission
#if [ 'id -u' != 0 ]; then
#	echo ${id}
#	echo "You do not have permission to run this script"
#	exit
#fi

# Test parameters
if [ $# -ne 1 ]; then
	usage
fi

if [ "$1" = "load" ]; then
	insmodules

elif [ "$1" = "remove" ]; then
	rmmodules

elif [ "$1" = "status" ]; then
	status

else
	usage
fi

