#!/bin/sh

#MODDIR= "/usr/realtime"
#MODULES= /usr/realtime/modules/rtai_hal.ko \
#		 /usr/realtime/modules/rtai_lxrt.ko 

usage () {
	echo "Usage: "
    echo "./rtai_modules_ctrl -l: load the modules"
	echo "./rtai_modules_ctrl -r: remove the modules"
	exit
}

insmodules () {	
	insmod /usr/realtime/modules/rtai_hal.ko
	insmod /usr/realtime/modules/rtai_lxrt.ko
	insmod /usr/realtime/modules/rtai_sem.ko
	insmod /usr/realtime/modules/rtai_mbx.ko
	insmod /usr/realtime/modules/rtai_msg.ko
	insmod /usr/realtime/modules/rtai_netrpc.ko ThisSoftNode="127.0.0.1"
}

rmmodules() {
	rmmod rtai_netrpc
	rmmod rtai_msg
	rmmod rtai_mbx
	rmmod rtai_sem
	rmmod rtai_lxrt
	rmmod rtai_hal
}

#Test permission
#if [ 'id -u' != 0 ]; then
#	echo ${id}
#	echo "You do not have permission to run this script"
#	exit
#fi

# Test parameters
if [ $# -ne 1 ]; then
	usage
fi

if [ "$1" = "-l" ]; then
	insmodules
elif [ "$1" = "-r" ]; then
	rmmodules
else
	usage
fi

